CREATE USER 'backup'@'localhost' IDENTIFIED BY 'Mt2(8eH5232Nb$3dw8s';
GRANT SELECT, INSERT, CREATE, RELOAD, PROCESS, SUPER, LOCK TABLES, REPLICATION CLIENT, SHOW VIEW, EVENT, CREATE TABLESPACE ON *.* TO 'backup'@'localhost';
